import { createSlice, PayloadAction } from '@reduxjs/toolkit';

export type CardData = {
  title: string;
  img: string;
  id?: number;
  date: string;
};
export type CardList = {
  list: CardData[];
};
export const initialState: CardList = {
  list: [
    {
      title: 'History quiz',
      img: 'https://i.ytimg.com/vi/s6yKBM3meeE/maxresdefault.jpg',
      date: '2022-09-06 03:00',
      id: 1,
    },
    {
      title: 'Programming quiz',
      img: 'https://obrmos.ru/kur/kur_dr/comp/img/pr.jpg',
      date: '2022-10-25 13:00',
      id: 2,
    },
    {
      title: 'Art quiz',
      img: 'https://artinvestment.ru/lolo/yan/yan-main.jpg',
      date: '2023-01-06 23:00',
      id: 3,
    },
    {
      title: 'Literature quiz',
      img: 'https://static.mk.ru/upload/entities/2019/04/11/23/articles/detailPicture/ec/ac/6d/01/306db442fae94a1476ddba3306b1f42f.jpg',
      date: '2023-02-01 03:00',
      id: 4,
    },
    {
      title: 'Musical quiz',
      img: 'https://sadpanda.cn/wordpress/wp-content/uploads/2016/04/62c72e3218c9921f1ac0f28aba96f6c9wood-background-music-beat-wallchan-665381_1015x571.jpg',
      date: '2022-12-10 03:00',
      id: 5,
    },
  ],
};
export const cardSlice = createSlice({
  name: 'cards',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    addCardReduser: (state, action: PayloadAction<CardData>) => {
      state.list.push(action.payload);
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

console.log(initialState);
export const { addCardReduser } = cardSlice.actions;

export default cardSlice.reducer;
